import asyncio

import httpx
import pytest
from goldenloop_demo_agent import run_case as demo_run_case

from goldenloop_api.db import CaseRevision, ChatSession, Event

from .conftest import publish, wait_for


@pytest.mark.parametrize(
    "check",
    [
        {"kind": "unknown", "config": {}},
        {"kind": "content_contains", "config": {}},
        {"kind": "exact_match", "config": {"value": ""}},
        {"kind": "tool_required", "config": {"tool": "lookup_customer", "min": 0}},
        {"kind": "tool_required", "config": {"tool": "lookup_customer", "min": 2, "max": 1}},
        {"kind": "tool_forbidden", "config": {"tool": "lookup_customer", "max": 2}},
        {"kind": "tool_order", "config": {"tools": [""]}},
        {
            "kind": "tool_arguments",
            "config": {"tool": "lookup_customer", "path": "id", "operator": "bogus", "value": 1},
        },
        {"kind": "json_schema", "config": {"schema": {"type": "bogus"}}},
        {"kind": "json_schema", "config": {"schema": {"$ref": "https://example.com/schema"}}},
        {"kind": "judge", "config": {"rubric": "Correctness", "threshold": 2}},
        {"kind": "judge", "config": {"rubric": "", "threshold": 0.5}},
    ],
)
async def test_invalid_checks_stay_candidates(client, case_payload, check):
    case_payload["checks"].append({**check, "required": False})
    response = await client.post("/api/v1/cases", json={"case": case_payload})
    assert response.status_code == 201
    case_id = response.json()["case"]["id"]
    response = await client.post(f"/api/v1/cases/{case_id}/approve", json={"revision": 1, "reason": "Review"})
    assert response.status_code == 422, response.text
    record = (await client.get(f"/api/v1/cases/{case_id}")).json()
    assert record["status"] == "candidate" and record["reviewer"] is None
    response = await client.post(
        "/api/v1/dataset-releases",
        json={"name": "invalid", "case_ids": [case_id], "expected_revisions": {case_id: 1}},
    )
    assert response.status_code == 409


async def test_publication_revalidates_existing_approval(client, app, case_payload):
    case, _ = await publish(client, case_payload)
    async with app.state.db.write() as session:
        row = await session.get(CaseRevision, (case["id"], 1))
        row.payload = {
            **row.payload,
            "checks": [
                {"id": "old-invalid", "kind": "unsupported", "required": True, "turn": None, "config": {}}
            ],
        }
    response = await client.post(
        "/api/v1/dataset-releases",
        json={"name": "invalid", "case_ids": [case["id"]], "expected_revisions": {case["id"]: 1}},
    )
    assert response.status_code == 422


async def test_approval_does_not_require_agent_to_pass(client, monkeypatch):
    async def forbidden(*args, **kwargs):
        raise AssertionError("Approval must not call the agent")

    monkeypatch.setattr("goldenloop_api.runner.run_case", forbidden)
    case = {
        "title": "Valid failing assertion",
        "turns": [{"user": "C-123"}],
        "checks": [
            {"kind": "exact_match", "config": {"value": "an answer not generated by this agent"}},
            {"kind": "judge", "config": {"rubric": "Correctness", "threshold": 0.8}},
        ],
    }
    await publish(client, case)


async def test_chat_continues_persisted_answers_without_replaying_tools(client, app, monkeypatch):
    invocations = []

    async def observed(case, revision, mode):
        invocations.append([turn.user for turn in case.turns])
        return await demo_run_case(case, revision=revision, mode=mode)

    monkeypatch.setattr("goldenloop_api.runner.run_case", observed)
    chat = (await client.post("/api/v1/chat-sessions", json={"agent_revision": "fixed"})).json()
    path = f"/api/v1/chat-sessions/{chat['id']}"
    await client.post(path + "/messages", json={"content": "Look up C-123"})
    first = await wait_for(client, path)
    # Simulate an earlier agent build's generated answer. The persisted history is authoritative.
    async with app.state.db.write() as session:
        row = await session.get(ChatSession, chat["id"])
        row.messages = [row.messages[0], {**row.messages[1], "content": "Previously generated unique answer"}]
    await client.post(path + "/messages", json={"content": "Repeat the answer"})
    second = await wait_for(client, path)
    assert second["messages"][-1]["content"] == "From my previous answer: Previously generated unique answer"
    assert second["tool_calls"] == first["tool_calls"]
    await client.post(path + "/messages", json={"content": "Look up C-999"})
    third = await wait_for(client, path)
    assert invocations == [["Look up C-123"], ["Repeat the answer"], ["Look up C-999"]]
    assert [call["turn"] for call in third["tool_calls"]] == [0, 2]
    assert len({call["id"] for call in third["tool_calls"]}) == 2
    assert "C-999" in third["messages"][-1]["content"]
    assert third["messages"][:4] == second["messages"]


async def test_chat_incomplete_trace_is_not_completed(client, monkeypatch):
    async def incomplete(case, revision, mode):
        observation = await demo_run_case(case, revision=revision, mode=mode)
        observation.trace_complete = False
        return observation

    monkeypatch.setattr("goldenloop_api.runner.run_case", incomplete)
    chat = (await client.post("/api/v1/chat-sessions", json={"agent_revision": "fixed"})).json()
    path = f"/api/v1/chat-sessions/{chat['id']}"
    await client.post(path + "/messages", json={"content": "C-123"})
    result = await wait_for(client, path)
    assert result["status"] == "failed" and not result["trace_complete"]


async def test_sse_drains_multiple_batches_before_terminal_close(client, app):
    chat = (await client.post("/api/v1/chat-sessions", json={"agent_revision": "fixed"})).json()
    async with app.state.db.write() as session:
        for index in range(205):
            session.add(Event(stream="chat:" + chat["id"], kind="message", payload={"index": index}))
    path = f"/api/v1/chat-sessions/{chat['id']}/events"
    response = await client.get(path)
    ids = [int(line[4:]) for line in response.text.splitlines() if line.startswith("id: ")]
    assert len(ids) == 205 and ids == sorted(set(ids))
    resumed = await client.get(path, headers={"Last-Event-ID": str(ids[99])})
    assert resumed.text.count("event: message") == 105
    assert (await client.get(path + "?after=9999999999999999999999999999")).status_code == 422


@pytest.mark.parametrize(
    "peer,host,origin",
    [
        ("127.0.0.1", "127.0.0.1:8000", "http://localhost:5173"),
        ("::1", "[::1]:8000", "http://[::1]:5173"),
        ("127.0.0.1", "localhost:8000", "http://127.0.0.1:5173"),
    ],
)
async def test_vite_proxy_local_origins(app, peer, host, origin):
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app, client=(peer, 12345)), base_url="http://localhost"
    ) as client:
        response = await client.post(
            "/api/v1/chat-sessions",
            json={"agent_revision": "fixed"},
            headers={"host": host, "origin": origin, "sec-fetch-site": "same-origin"},
        )
        assert response.status_code == 201


async def test_disconnect_does_not_cancel_run(client, case_payload, monkeypatch):
    # The command is durable independently of opening or keeping an SSE connection.
    invoked = asyncio.Event()
    finish = asyncio.Event()

    async def delayed(case, revision, mode):
        invoked.set()
        await finish.wait()
        return await demo_run_case(case, revision=revision, mode=mode)

    monkeypatch.setattr("goldenloop_api.runner.run_case", delayed)
    _, release = await publish(client, case_payload)
    run = (
        await client.post(
            "/api/v1/evaluation-runs",
            json={"release_id": release["id"], "agent_revision": "fixed", "idempotency_key": "disconnect"},
        )
    ).json()
    await asyncio.wait_for(invoked.wait(), 2)
    stream_task = asyncio.create_task(client.get(f"/api/v1/evaluation-runs/{run['id']}/events"))
    await asyncio.sleep(0.02)
    stream_task.cancel()
    with pytest.raises(asyncio.CancelledError):
        await stream_task
    finish.set()
    result = await wait_for(client, f"/api/v1/evaluation-runs/{run['id']}")
    assert result["status"] == "completed" and result["gate"] == "pass"
